name: Auto Approve

permissions:
  pull-requests: write

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
jobs:
  approve:
    if: |
      github.event.pull_request.user.login == github.repository_owner
      && ! github.event.pull_request.draft
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v3
